/**
 * generated by Xtext 2.15.0
 */
package org.xtext.browser.mydsl.ide;

import org.xtext.browser.mydsl.ide.AbstractMyDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyDslIdeModule extends AbstractMyDslIdeModule {
}
