/**
 * generated by Xtext 2.15.0
 */
package org.xtext.browser.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.browser.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/browser/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.TestImpl <em>Test</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.TestImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getTest()
   * @generated
   */
  int TEST = 0;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST__NUMBER = 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST__BODY = 1;

  /**
   * The number of structural features of the '<em>Test</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.INSTRUCTIONImpl <em>INSTRUCTION</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.INSTRUCTIONImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getINSTRUCTION()
   * @generated
   */
  int INSTRUCTION = 1;

  /**
   * The number of structural features of the '<em>INSTRUCTION</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.OpenImpl <em>Open</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.OpenImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getOpen()
   * @generated
   */
  int OPEN = 2;

  /**
   * The feature id for the '<em><b>Browser</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN__BROWSER = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Open</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.GoToImpl <em>Go To</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.GoToImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getGoTo()
   * @generated
   */
  int GO_TO = 3;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_TO__URL = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Go To</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_TO_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.VerifyImpl <em>Verify</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.VerifyImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getVerify()
   * @generated
   */
  int VERIFY = 4;

  /**
   * The number of structural features of the '<em>Verify</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.TYPE_VERIFYImpl <em>TYPE VERIFY</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.TYPE_VERIFYImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getTYPE_VERIFY()
   * @generated
   */
  int TYPE_VERIFY = 5;

  /**
   * The number of structural features of the '<em>TYPE VERIFY</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_VERIFY_FEATURE_COUNT = VERIFY_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.ContainsImpl <em>Contains</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.ContainsImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getContains()
   * @generated
   */
  int CONTAINS = 6;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINS__TYPE = TYPE_VERIFY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Parametre</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINS__PARAMETRE = TYPE_VERIFY_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Contains</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINS_FEATURE_COUNT = TYPE_VERIFY_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.TYPE_PARAMETREImpl <em>TYPE PARAMETRE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.TYPE_PARAMETREImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getTYPE_PARAMETRE()
   * @generated
   */
  int TYPE_PARAMETRE = 7;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_PARAMETRE__VALUE = 0;

  /**
   * The number of structural features of the '<em>TYPE PARAMETRE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_PARAMETRE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.ValueImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getValue()
   * @generated
   */
  int VALUE = 8;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__VALUE = TYPE_PARAMETRE__VALUE;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = TYPE_PARAMETRE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.VarImpl <em>Var</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.VarImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getVar()
   * @generated
   */
  int VAR = 9;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR__VALUE = TYPE_PARAMETRE__VALUE;

  /**
   * The number of structural features of the '<em>Var</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_FEATURE_COUNT = TYPE_PARAMETRE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.EqualImpl <em>Equal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.EqualImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getEqual()
   * @generated
   */
  int EQUAL = 10;

  /**
   * The feature id for the '<em><b>Var1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL__VAR1 = TYPE_VERIFY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Var2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL__VAR2 = TYPE_VERIFY_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Equal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL_FEATURE_COUNT = TYPE_VERIFY_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.ClickImpl <em>Click</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.ClickImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getClick()
   * @generated
   */
  int CLICK = 11;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__TYPE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Parametre</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__PARAMETRE = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Click</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.InsertImpl <em>Insert</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.InsertImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getInsert()
   * @generated
   */
  int INSERT = 12;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__TYPE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__NAME = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Parametre</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__PARAMETRE = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Insert</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.UncheckImpl <em>Uncheck</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.UncheckImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getUncheck()
   * @generated
   */
  int UNCHECK = 13;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNCHECK__TYPE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Uncheck</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNCHECK_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.TYPE_CHECK_UNCHECKImpl <em>TYPE CHECK UNCHECK</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.TYPE_CHECK_UNCHECKImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getTYPE_CHECK_UNCHECK()
   * @generated
   */
  int TYPE_CHECK_UNCHECK = 14;

  /**
   * The feature id for the '<em><b>Tableau</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_CHECK_UNCHECK__TABLEAU = 0;

  /**
   * The number of structural features of the '<em>TYPE CHECK UNCHECK</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_CHECK_UNCHECK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.CheckImpl <em>Check</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.CheckImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getCheck()
   * @generated
   */
  int CHECK = 15;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__TYPE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Check</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.ChooseImpl <em>Choose</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.ChooseImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getChoose()
   * @generated
   */
  int CHOOSE = 16;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOOSE__TYPE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Parametre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOOSE__PARAMETRE = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOOSE__NAME = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Choose</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOOSE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.VariableImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Instruction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__INSTRUCTION = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.TYPE_INSTRUCTIONImpl <em>TYPE INSTRUCTION</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.TYPE_INSTRUCTIONImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getTYPE_INSTRUCTION()
   * @generated
   */
  int TYPE_INSTRUCTION = 18;

  /**
   * The number of structural features of the '<em>TYPE INSTRUCTION</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_INSTRUCTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.ReadImpl <em>Read</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.ReadImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getRead()
   * @generated
   */
  int READ = 19;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ__TYPE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Parametre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ__PARAMETRE = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Read</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.CountImpl <em>Count</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.CountImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getCount()
   * @generated
   */
  int COUNT = 20;

  /**
   * The feature id for the '<em><b>Parametre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNT__PARAMETRE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Count</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNT_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.PasteImpl <em>Paste</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.PasteImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getPaste()
   * @generated
   */
  int PASTE = 21;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASTE__TYPE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Parametre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASTE__PARAMETRE = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Paste</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASTE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.ForImpl <em>For</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.ForImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getFor()
   * @generated
   */
  int FOR = 22;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR__NAME = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Tableau</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR__TABLEAU = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>For</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.browser.mydsl.myDsl.impl.EndForImpl <em>End For</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browser.mydsl.myDsl.impl.EndForImpl
   * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getEndFor()
   * @generated
   */
  int END_FOR = 23;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_FOR__NAME = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>End For</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_FOR_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.Test <em>Test</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Test
   * @generated
   */
  EClass getTest();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.Test#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Test#getNumber()
   * @see #getTest()
   * @generated
   */
  EAttribute getTest_Number();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.browser.mydsl.myDsl.Test#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Body</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Test#getBody()
   * @see #getTest()
   * @generated
   */
  EReference getTest_Body();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.INSTRUCTION <em>INSTRUCTION</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>INSTRUCTION</em>'.
   * @see org.xtext.browser.mydsl.myDsl.INSTRUCTION
   * @generated
   */
  EClass getINSTRUCTION();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.Open <em>Open</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Open</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Open
   * @generated
   */
  EClass getOpen();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.Open#getBrowser <em>Browser</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Browser</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Open#getBrowser()
   * @see #getOpen()
   * @generated
   */
  EAttribute getOpen_Browser();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.GoTo <em>Go To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Go To</em>'.
   * @see org.xtext.browser.mydsl.myDsl.GoTo
   * @generated
   */
  EClass getGoTo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.GoTo#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.browser.mydsl.myDsl.GoTo#getUrl()
   * @see #getGoTo()
   * @generated
   */
  EAttribute getGoTo_Url();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.Verify <em>Verify</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Verify</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Verify
   * @generated
   */
  EClass getVerify();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.TYPE_VERIFY <em>TYPE VERIFY</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>TYPE VERIFY</em>'.
   * @see org.xtext.browser.mydsl.myDsl.TYPE_VERIFY
   * @generated
   */
  EClass getTYPE_VERIFY();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.Contains <em>Contains</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Contains</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Contains
   * @generated
   */
  EClass getContains();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.Contains#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Contains#getType()
   * @see #getContains()
   * @generated
   */
  EAttribute getContains_Type();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.browser.mydsl.myDsl.Contains#getParametre <em>Parametre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parametre</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Contains#getParametre()
   * @see #getContains()
   * @generated
   */
  EReference getContains_Parametre();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.TYPE_PARAMETRE <em>TYPE PARAMETRE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>TYPE PARAMETRE</em>'.
   * @see org.xtext.browser.mydsl.myDsl.TYPE_PARAMETRE
   * @generated
   */
  EClass getTYPE_PARAMETRE();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.TYPE_PARAMETRE#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.browser.mydsl.myDsl.TYPE_PARAMETRE#getValue()
   * @see #getTYPE_PARAMETRE()
   * @generated
   */
  EAttribute getTYPE_PARAMETRE_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.Var <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Var
   * @generated
   */
  EClass getVar();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.Equal <em>Equal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equal</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Equal
   * @generated
   */
  EClass getEqual();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.Equal#getVar1 <em>Var1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var1</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Equal#getVar1()
   * @see #getEqual()
   * @generated
   */
  EAttribute getEqual_Var1();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.Equal#getVar2 <em>Var2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var2</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Equal#getVar2()
   * @see #getEqual()
   * @generated
   */
  EAttribute getEqual_Var2();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.Click <em>Click</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Click
   * @generated
   */
  EClass getClick();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.Click#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Click#getType()
   * @see #getClick()
   * @generated
   */
  EAttribute getClick_Type();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.browser.mydsl.myDsl.Click#getParametre <em>Parametre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parametre</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Click#getParametre()
   * @see #getClick()
   * @generated
   */
  EReference getClick_Parametre();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.Insert <em>Insert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insert</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Insert
   * @generated
   */
  EClass getInsert();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.Insert#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Insert#getType()
   * @see #getInsert()
   * @generated
   */
  EAttribute getInsert_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.Insert#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Insert#getName()
   * @see #getInsert()
   * @generated
   */
  EAttribute getInsert_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.browser.mydsl.myDsl.Insert#getParametre <em>Parametre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parametre</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Insert#getParametre()
   * @see #getInsert()
   * @generated
   */
  EReference getInsert_Parametre();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.Uncheck <em>Uncheck</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Uncheck</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Uncheck
   * @generated
   */
  EClass getUncheck();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.browser.mydsl.myDsl.Uncheck#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Uncheck#getType()
   * @see #getUncheck()
   * @generated
   */
  EReference getUncheck_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.TYPE_CHECK_UNCHECK <em>TYPE CHECK UNCHECK</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>TYPE CHECK UNCHECK</em>'.
   * @see org.xtext.browser.mydsl.myDsl.TYPE_CHECK_UNCHECK
   * @generated
   */
  EClass getTYPE_CHECK_UNCHECK();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.browser.mydsl.myDsl.TYPE_CHECK_UNCHECK#getTableau <em>Tableau</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Tableau</em>'.
   * @see org.xtext.browser.mydsl.myDsl.TYPE_CHECK_UNCHECK#getTableau()
   * @see #getTYPE_CHECK_UNCHECK()
   * @generated
   */
  EAttribute getTYPE_CHECK_UNCHECK_Tableau();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.Check <em>Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Check</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Check
   * @generated
   */
  EClass getCheck();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.browser.mydsl.myDsl.Check#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Check#getType()
   * @see #getCheck()
   * @generated
   */
  EReference getCheck_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.Choose <em>Choose</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Choose</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Choose
   * @generated
   */
  EClass getChoose();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.Choose#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Choose#getType()
   * @see #getChoose()
   * @generated
   */
  EAttribute getChoose_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.Choose#getParametre <em>Parametre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Parametre</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Choose#getParametre()
   * @see #getChoose()
   * @generated
   */
  EAttribute getChoose_Parametre();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.Choose#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Choose#getName()
   * @see #getChoose()
   * @generated
   */
  EAttribute getChoose_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.browser.mydsl.myDsl.Variable#getInstruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Instruction</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Variable#getInstruction()
   * @see #getVariable()
   * @generated
   */
  EReference getVariable_Instruction();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.TYPE_INSTRUCTION <em>TYPE INSTRUCTION</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>TYPE INSTRUCTION</em>'.
   * @see org.xtext.browser.mydsl.myDsl.TYPE_INSTRUCTION
   * @generated
   */
  EClass getTYPE_INSTRUCTION();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.Read <em>Read</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Read</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Read
   * @generated
   */
  EClass getRead();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.Read#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Read#getType()
   * @see #getRead()
   * @generated
   */
  EAttribute getRead_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.Read#getParametre <em>Parametre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Parametre</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Read#getParametre()
   * @see #getRead()
   * @generated
   */
  EAttribute getRead_Parametre();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.Count <em>Count</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Count</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Count
   * @generated
   */
  EClass getCount();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.Count#getParametre <em>Parametre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Parametre</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Count#getParametre()
   * @see #getCount()
   * @generated
   */
  EAttribute getCount_Parametre();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.Paste <em>Paste</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Paste</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Paste
   * @generated
   */
  EClass getPaste();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.Paste#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Paste#getType()
   * @see #getPaste()
   * @generated
   */
  EAttribute getPaste_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.Paste#getParametre <em>Parametre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Parametre</em>'.
   * @see org.xtext.browser.mydsl.myDsl.Paste#getParametre()
   * @see #getPaste()
   * @generated
   */
  EAttribute getPaste_Parametre();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.For <em>For</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>For</em>'.
   * @see org.xtext.browser.mydsl.myDsl.For
   * @generated
   */
  EClass getFor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.For#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.browser.mydsl.myDsl.For#getName()
   * @see #getFor()
   * @generated
   */
  EAttribute getFor_Name();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.browser.mydsl.myDsl.For#getTableau <em>Tableau</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Tableau</em>'.
   * @see org.xtext.browser.mydsl.myDsl.For#getTableau()
   * @see #getFor()
   * @generated
   */
  EAttribute getFor_Tableau();

  /**
   * Returns the meta object for class '{@link org.xtext.browser.mydsl.myDsl.EndFor <em>End For</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>End For</em>'.
   * @see org.xtext.browser.mydsl.myDsl.EndFor
   * @generated
   */
  EClass getEndFor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browser.mydsl.myDsl.EndFor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.browser.mydsl.myDsl.EndFor#getName()
   * @see #getEndFor()
   * @generated
   */
  EAttribute getEndFor_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.TestImpl <em>Test</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.TestImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getTest()
     * @generated
     */
    EClass TEST = eINSTANCE.getTest();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST__NUMBER = eINSTANCE.getTest_Number();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST__BODY = eINSTANCE.getTest_Body();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.INSTRUCTIONImpl <em>INSTRUCTION</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.INSTRUCTIONImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getINSTRUCTION()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getINSTRUCTION();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.OpenImpl <em>Open</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.OpenImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getOpen()
     * @generated
     */
    EClass OPEN = eINSTANCE.getOpen();

    /**
     * The meta object literal for the '<em><b>Browser</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPEN__BROWSER = eINSTANCE.getOpen_Browser();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.GoToImpl <em>Go To</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.GoToImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getGoTo()
     * @generated
     */
    EClass GO_TO = eINSTANCE.getGoTo();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GO_TO__URL = eINSTANCE.getGoTo_Url();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.VerifyImpl <em>Verify</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.VerifyImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getVerify()
     * @generated
     */
    EClass VERIFY = eINSTANCE.getVerify();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.TYPE_VERIFYImpl <em>TYPE VERIFY</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.TYPE_VERIFYImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getTYPE_VERIFY()
     * @generated
     */
    EClass TYPE_VERIFY = eINSTANCE.getTYPE_VERIFY();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.ContainsImpl <em>Contains</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.ContainsImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getContains()
     * @generated
     */
    EClass CONTAINS = eINSTANCE.getContains();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTAINS__TYPE = eINSTANCE.getContains_Type();

    /**
     * The meta object literal for the '<em><b>Parametre</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTAINS__PARAMETRE = eINSTANCE.getContains_Parametre();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.TYPE_PARAMETREImpl <em>TYPE PARAMETRE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.TYPE_PARAMETREImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getTYPE_PARAMETRE()
     * @generated
     */
    EClass TYPE_PARAMETRE = eINSTANCE.getTYPE_PARAMETRE();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_PARAMETRE__VALUE = eINSTANCE.getTYPE_PARAMETRE_Value();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.ValueImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.VarImpl <em>Var</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.VarImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getVar()
     * @generated
     */
    EClass VAR = eINSTANCE.getVar();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.EqualImpl <em>Equal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.EqualImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getEqual()
     * @generated
     */
    EClass EQUAL = eINSTANCE.getEqual();

    /**
     * The meta object literal for the '<em><b>Var1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EQUAL__VAR1 = eINSTANCE.getEqual_Var1();

    /**
     * The meta object literal for the '<em><b>Var2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EQUAL__VAR2 = eINSTANCE.getEqual_Var2();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.ClickImpl <em>Click</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.ClickImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getClick()
     * @generated
     */
    EClass CLICK = eINSTANCE.getClick();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK__TYPE = eINSTANCE.getClick_Type();

    /**
     * The meta object literal for the '<em><b>Parametre</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLICK__PARAMETRE = eINSTANCE.getClick_Parametre();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.InsertImpl <em>Insert</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.InsertImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getInsert()
     * @generated
     */
    EClass INSERT = eINSTANCE.getInsert();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT__TYPE = eINSTANCE.getInsert_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT__NAME = eINSTANCE.getInsert_Name();

    /**
     * The meta object literal for the '<em><b>Parametre</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT__PARAMETRE = eINSTANCE.getInsert_Parametre();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.UncheckImpl <em>Uncheck</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.UncheckImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getUncheck()
     * @generated
     */
    EClass UNCHECK = eINSTANCE.getUncheck();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNCHECK__TYPE = eINSTANCE.getUncheck_Type();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.TYPE_CHECK_UNCHECKImpl <em>TYPE CHECK UNCHECK</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.TYPE_CHECK_UNCHECKImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getTYPE_CHECK_UNCHECK()
     * @generated
     */
    EClass TYPE_CHECK_UNCHECK = eINSTANCE.getTYPE_CHECK_UNCHECK();

    /**
     * The meta object literal for the '<em><b>Tableau</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_CHECK_UNCHECK__TABLEAU = eINSTANCE.getTYPE_CHECK_UNCHECK_Tableau();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.CheckImpl <em>Check</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.CheckImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getCheck()
     * @generated
     */
    EClass CHECK = eINSTANCE.getCheck();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECK__TYPE = eINSTANCE.getCheck_Type();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.ChooseImpl <em>Choose</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.ChooseImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getChoose()
     * @generated
     */
    EClass CHOOSE = eINSTANCE.getChoose();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOOSE__TYPE = eINSTANCE.getChoose_Type();

    /**
     * The meta object literal for the '<em><b>Parametre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOOSE__PARAMETRE = eINSTANCE.getChoose_Parametre();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOOSE__NAME = eINSTANCE.getChoose_Name();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.VariableImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '<em><b>Instruction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE__INSTRUCTION = eINSTANCE.getVariable_Instruction();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.TYPE_INSTRUCTIONImpl <em>TYPE INSTRUCTION</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.TYPE_INSTRUCTIONImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getTYPE_INSTRUCTION()
     * @generated
     */
    EClass TYPE_INSTRUCTION = eINSTANCE.getTYPE_INSTRUCTION();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.ReadImpl <em>Read</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.ReadImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getRead()
     * @generated
     */
    EClass READ = eINSTANCE.getRead();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute READ__TYPE = eINSTANCE.getRead_Type();

    /**
     * The meta object literal for the '<em><b>Parametre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute READ__PARAMETRE = eINSTANCE.getRead_Parametre();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.CountImpl <em>Count</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.CountImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getCount()
     * @generated
     */
    EClass COUNT = eINSTANCE.getCount();

    /**
     * The meta object literal for the '<em><b>Parametre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COUNT__PARAMETRE = eINSTANCE.getCount_Parametre();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.PasteImpl <em>Paste</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.PasteImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getPaste()
     * @generated
     */
    EClass PASTE = eINSTANCE.getPaste();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PASTE__TYPE = eINSTANCE.getPaste_Type();

    /**
     * The meta object literal for the '<em><b>Parametre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PASTE__PARAMETRE = eINSTANCE.getPaste_Parametre();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.ForImpl <em>For</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.ForImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getFor()
     * @generated
     */
    EClass FOR = eINSTANCE.getFor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FOR__NAME = eINSTANCE.getFor_Name();

    /**
     * The meta object literal for the '<em><b>Tableau</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FOR__TABLEAU = eINSTANCE.getFor_Tableau();

    /**
     * The meta object literal for the '{@link org.xtext.browser.mydsl.myDsl.impl.EndForImpl <em>End For</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browser.mydsl.myDsl.impl.EndForImpl
     * @see org.xtext.browser.mydsl.myDsl.impl.MyDslPackageImpl#getEndFor()
     * @generated
     */
    EClass END_FOR = eINSTANCE.getEndFor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute END_FOR__NAME = eINSTANCE.getEndFor_Name();

  }

} //MyDslPackage
