/**
 * generated by Xtext 2.15.0
 */
package org.xtext.browser.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Open</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.browser.mydsl.myDsl.Open#getBrowser <em>Browser</em>}</li>
 * </ul>
 *
 * @see org.xtext.browser.mydsl.myDsl.MyDslPackage#getOpen()
 * @model
 * @generated
 */
public interface Open extends INSTRUCTION
{
  /**
   * Returns the value of the '<em><b>Browser</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Browser</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Browser</em>' attribute.
   * @see #setBrowser(String)
   * @see org.xtext.browser.mydsl.myDsl.MyDslPackage#getOpen_Browser()
   * @model
   * @generated
   */
  String getBrowser();

  /**
   * Sets the value of the '{@link org.xtext.browser.mydsl.myDsl.Open#getBrowser <em>Browser</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Browser</em>' attribute.
   * @see #getBrowser()
   * @generated
   */
  void setBrowser(String value);

} // Open
