/**
 * generated by Xtext 2.15.0
 */
package org.xtext.browser.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>TYPE CHECK UNCHECK</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.browser.mydsl.myDsl.TYPE_CHECK_UNCHECK#getTableau <em>Tableau</em>}</li>
 * </ul>
 *
 * @see org.xtext.browser.mydsl.myDsl.MyDslPackage#getTYPE_CHECK_UNCHECK()
 * @model
 * @generated
 */
public interface TYPE_CHECK_UNCHECK extends EObject
{
  /**
   * Returns the value of the '<em><b>Tableau</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tableau</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tableau</em>' attribute list.
   * @see org.xtext.browser.mydsl.myDsl.MyDslPackage#getTYPE_CHECK_UNCHECK_Tableau()
   * @model unique="false"
   * @generated
   */
  EList<String> getTableau();

} // TYPE_CHECK_UNCHECK
