/**
 * generated by Xtext 2.15.0
 */
package org.xtext.browser.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>TYPE INSTRUCTION</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.browser.mydsl.myDsl.MyDslPackage#getTYPE_INSTRUCTION()
 * @model
 * @generated
 */
public interface TYPE_INSTRUCTION extends EObject
{
} // TYPE_INSTRUCTION
