/**
 * generated by Xtext 2.15.0
 */
package org.xtext.browser.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>TYPE VERIFY</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.browser.mydsl.myDsl.MyDslPackage#getTYPE_VERIFY()
 * @model
 * @generated
 */
public interface TYPE_VERIFY extends Verify
{
} // TYPE_VERIFY
