/**
 * generated by Xtext 2.15.0
 */
package org.xtext.browser.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.browser.mydsl.myDsl.MyDslPackage#getVar()
 * @model
 * @generated
 */
public interface Var extends TYPE_PARAMETRE
{
} // Var
