/**
 * generated by Xtext 2.15.0
 */
package org.xtext.browser.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Verify</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.browser.mydsl.myDsl.MyDslPackage#getVerify()
 * @model
 * @generated
 */
public interface Verify extends INSTRUCTION
{
} // Verify
