/**
 * generated by Xtext 2.15.0
 */
package org.xtext.browser.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.browser.mydsl.myDsl.INSTRUCTION;
import org.xtext.browser.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>INSTRUCTION</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class INSTRUCTIONImpl extends MinimalEObjectImpl.Container implements INSTRUCTION
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected INSTRUCTIONImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.INSTRUCTION;
  }

} //INSTRUCTIONImpl
