/**
 * generated by Xtext 2.15.0
 */
package org.xtext.browser.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.browser.mydsl.myDsl.MyDslPackage;
import org.xtext.browser.mydsl.myDsl.TYPE_VERIFY;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>TYPE VERIFY</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TYPE_VERIFYImpl extends VerifyImpl implements TYPE_VERIFY
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TYPE_VERIFYImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.TYPE_VERIFY;
  }

} //TYPE_VERIFYImpl
