/**
 * generated by Xtext 2.15.0
 */
package org.xtext.browser.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.browser.mydsl.myDsl.MyDslPackage;
import org.xtext.browser.mydsl.myDsl.TYPE_INSTRUCTION;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>TYPE INSTRUCTION</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TYPE_INSTRUCTIONImpl extends MinimalEObjectImpl.Container implements TYPE_INSTRUCTION
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TYPE_INSTRUCTIONImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.TYPE_INSTRUCTION;
  }

} //TYPE_INSTRUCTIONImpl
