/**
 * generated by Xtext 2.15.0
 */
package org.xtext.browser.mydsl;

import org.xtext.browser.mydsl.AbstractMyDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
