/**
 * generated by Xtext 2.15.0
 */
package org.xtext.browser.mydsl.ui.contentassist;

import org.xtext.browser.mydsl.ui.contentassist.AbstractMyDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MyDslProposalProvider extends AbstractMyDslProposalProvider {
}
